#!/usr/bin/env bash
# desc: opencode desktop (official AppImage; self-updating)
# os: any
# check: test -x "$HOME/Applications/opencode-desktop.AppImage" && test -x "$HOME/.local/bin/opencode-desktop"
# prio: p2
set -euo pipefail

# OpenCode Desktop (the Electron GUI, v2).
#
# Source is the opencode.ai CDN, NOT the GitHub releases. `anomalyco/opencode`
# release assets are the *CLI* channel (its desktop AppImage reports
# X-AppImage-Version 1.18.34 and GitHub has no 2.0.x tag); the GUI is served
# from https://opencode.ai/files/bin/<version>/. The version is resolved from
# the /download/stable redirect so this never pins something stale.
#
# Installed as a plain AppImage under ~/Applications on purpose: the app
# auto-updates itself in place, which a read-only /nix/store path forbids
# (observed 2.0.22 -> 2.0.24, byte-identical to the CDN artifact). Do NOT
# repackage this into the Nix store — that is what breaks auto-update.
# See .agents/plans/21-self-updating-apps.

if [ "$(uname -s)" = Darwin ]; then
  if command -v brew >/dev/null 2>&1; then
    brew install --cask opencode-desktop
    exit 0
  fi
  echo "opencode-desktop: no Homebrew; install the dmg from https://opencode.ai/download" >&2
  exit 1
fi

app="$HOME/Applications/opencode-desktop.AppImage"
launcher="$HOME/.local/bin/opencode-desktop"
entry="$HOME/.local/share/applications/opencode-desktop.desktop"
icon="$HOME/.local/share/icons/hicolor/128x128/apps/opencode-desktop.png"

# Current stable version, read off the download redirect.
ver="$(curl -fsSI -o /dev/null -w '%{redirect_url}' \
  https://opencode.ai/download/stable/linux-x64-deb 2>/dev/null \
  | sed -nE 's|.*/files/bin/([^/]+)/.*|\1|p')"
[ -n "$ver" ] || { echo "could not resolve the opencode desktop version" >&2; exit 1; }
url="https://opencode.ai/files/bin/$ver/opencode-desktop-linux-x86_64.AppImage"

mkdir -p "$HOME/Applications" "$HOME/.local/bin" "$HOME/.local/share/applications"

if [ ! -x "$app" ]; then
  echo "downloading opencode desktop $ver"
  curl -fL --progress-bar -o "$app.tmp" "$url"
  chmod +x "$app.tmp"
  mv "$app.tmp" "$app"
else
  echo "opencode-desktop AppImage already present (it self-updates); left as is"
fi

# Icon comes from the AppImage itself, so nothing binary needs committing.
if [ ! -e "$icon" ]; then
  tmp="$(mktemp -d)"
  ( cd "$tmp" && "$app" --appimage-extract ai.opencode.desktop.png >/dev/null 2>&1 ) || true
  if [ -f "$tmp/squashfs-root/ai.opencode.desktop.png" ]; then
    mkdir -p "$(dirname "$icon")"
    cp "$tmp/squashfs-root/ai.opencode.desktop.png" "$icon"
  fi
  rm -rf "$tmp"
fi

# appimage-run is needed on NixOS (no /lib64/ld-linux); elsewhere the AppImage
# runs directly. Both keep self-update working.
cat > "$launcher" <<'LAUNCHER'
#!/usr/bin/env bash
# OpenCode Desktop — official upstream AppImage (v2).
# --no-sandbox mirrors the AppImage's own desktop entry (upstream default).
# Generated by setup/steps/71-opencode-desktop.sh; see
# .agents/plans/21-self-updating-apps.
if command -v appimage-run >/dev/null 2>&1 || [ -x "$HOME/.nix-profile/bin/appimage-run" ]; then
  command -v appimage-run >/dev/null 2>&1 || PATH="$HOME/.nix-profile/bin:$PATH"
  exec appimage-run "$HOME/Applications/opencode-desktop.AppImage" --no-sandbox "$@"
fi
exec "$HOME/Applications/opencode-desktop.AppImage" --no-sandbox "$@"
LAUNCHER
chmod +x "$launcher"

# Absolute Exec: a bare name would have to resolve through the session PATH,
# which GUI launchers do not always have (that is what broke this before).
cat > "$entry" <<DESKTOP
[Desktop Entry]
Type=Application
Name=OpenCode
GenericName=AI Coding Agent
Comment=Open-source AI coding agent
Exec=$launcher %U
Icon=opencode-desktop
Terminal=false
Categories=Development;
Keywords=opencode;ai;agent;coding;
MimeType=x-scheme-handler/opencode;
StartupWMClass=ai.opencode.desktop
DESKTOP

command -v update-desktop-database >/dev/null 2>&1 &&
  update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 || true

echo "opencode-desktop $ver installed"
